name: CI

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup Database
        run: docker-compose up -d && docker-compose up -d

      - name: Run tests
        run: make test
        env:
          DATABASE_NAME: api
          DATABASE_USER: root
          DATABASE_PASSWORD: root
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: 3306
        